### PR TITLE
win: fix can not find primary monitor crash

### PR DESCRIPTION
**Pull request by xuwanghu**
**Fix** 
https://bugs.chromium.org/p/chromium/issues/detail?id=1436572

**Root Cause:**
Consider this scenario, where you have two screens, called A and B, and B is set as the primary screen. “EnumDisplayMonitors” enumerates the screens, and call "GetMonitorInfo" in the callback function to obtain the screen information. There could be this timing:
1.call "EnumDisplayMonitors"
2.callback the A's screen handle, and get the information about A.
3.unplug the B
4.there will no more callback about B
5.the result of "EnumDisplayMonitors" will only have one screen, and the top left corner is not (0,0)

**Solution:**
Simply return an empty list, because in this scenario, a second "WM_DISPLAYCHANGE" message will come immediately.
**DCHECK does not work in Release mode.**

### CODE REVIEW

**Comment by xuwanghu** [comment]
may fix https://bugs.chromium.org/p/chromium/issues/detail?id=1436572

**Comment by xuwanghu** [comment]
**Root Cause:**  
Consider this scenario, where you have two screens, called A and B, and B is set as the primary screen. “EnumDisplayMonitors” enumerates the screens, and call "GetMonitorInfo" in the callback function to obtain the screen information. There could be this timing:

1. call "EnumDisplayMonitors"
1. callback the A's screen handle, and get the information about A.
1. unplug the B
1. there will no more callback about B
1. the result of "EnumDisplayMonitors" will only have one screen, and the top left corner is not (0,0)

**Solution:**  
Simply return an empty list, because in this scenario, a second "WM_DISPLAYCHANGE" message will come immediately.

**Comment by xuwanghu** [comment]
DCHECK does not work in Release mode to prevent crashes

**Comment by xuwanghu** [comment]
@pkasting @nornagon

**Comment by gz83** [comment]
@xuwanghu

I think you should try to submit your patch according to the following guidelines.

https://chromium.googlesource.com/chromium/src/+/HEAD/docs/contributing.md

**Comment by pkasting** [comment]
Indeed, this is merely a mirror of the source code, and we don't review patches here. Please follow the contributing guidelines linked above.

When you send your patch for review, please add a comment in the patch explaining how the conditional in question can be triggered, as it's not obvious without the description you've provided above.

**Comment by xuwanghu** [comment]
> 

sure

**Comment by xuwanghu** [comment]
Thanks for telling me that

**Pull request closed without merging**
