### PR TITLE
PDF: Add vi scrolling keys

### PR DESCRIPTION
**Pull request by JOT85**
Vimium is a popular extension for adding vim style keybindings to chrome. Due to how the PDF viewer is implemented, vimium, or other similar extensions, can't be used for scrolling within it.

Since the H, J, K and L keys have no other function when viewing a PDF (when not giving form input) I've added scrolling functionality to those keys.

I think there are a notable number of people who would appreciate this change (I know at least one other person who would and I don't know too many people and it's a feature which has been requested many times before: https://github.com/philc/vimium/issues/723, https://github.com/philc/vimium/issues/880, https://github.com/philc/vimium/issues/1243, https://github.com/philc/vimium/issues/2498, https://github.com/philc/vimium/issues/3340, etc) and it doesn't really effect users in any other way.

Thank you for your time!

### CODE REVIEW

**Comment by JOT85** [comment]
@googlebot I signed it!

**Comment by dj2** [comment]
Chromium CLs are reviewed on https://chromium-review.googlesource.com as opposed to Github. This is just a mirror of the official repo. Instead of pushing the PR to GitHub you should use `git cl upload` to send it to Gerrit.

Please see https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md for guidance on contributing to the project.

I'd also suggest filing a PDFium bug (https://crbug.com/pdfium) to discuss the enhancement and determine if it's an acceptable change.

**Comment by dj2** [comment]
Awesome, thank you.

**Comment by FuccDucc** [comment]
What is happening here (btw: [example 1](https://bugs.chromium.org/p/pdfium/issues/detail?id=1603), [example 2](https://bugs.chromium.org/p/chromium/issues/detail?id=575588#c9), [example 3 (comment by Lei Zhang)](https://chromium-review.googlesource.com/c/chromium/src/+/2498490/1#message-b4e9b3c3a534de25ca254ae290c6853c2dc03097)  is the perfect sketch of what happens when a random, well-willing open source developer like wants to contribute to Chromium - they are dense. Taking seriously only their own project members that are Google hires.. and using bad arguments (as in example 2) to deter anything from anyone unknown.

But yeah, what if they don't know any better.. those project members are just satisfying the system in place, as they are part of it. 

But ye, as you can see @JOT85, it's hard to contribute to a large project like this, you're going to run into walls no matter what. So maybe they dont deserve your efforts.

**Comment by doroniz** [comment]
Does anyone know why I do not receive notifications from the subscribe here and also of the project in general?

**Pull request closed without merging**
