### PR TITLE
About the Android compilation problem of version 100.0.4854.0 and above

### PR DESCRIPTION
**Pull request by emmaki**
Since 100.0.4854.0, there has been a problem that the Link fails to pass after Android compilation. The content is as follows: How to solve it?

```
ld.lld: error: undefined hidden symbol: __system_property_get
>>> referenced by cpu_model.c
>>>               cpu_model.c.o:(init_have_lse_atomics) in archive ../../third_party/llvm-build/Release+Asserts/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-aarch64-android.a
>>> did you mean: __system_property_set
>>> defined in: ../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/23/libc.so

ld.lld: error: undefined symbol: net::android::BindToNetwork(int, long)
>>> referenced by tcp_socket_posix.cc
>>>               thinlto-cache/llvmcache-D251DAA5ADB3151331297745F2EEB92F6332F6CB:(net::TCPSocketPosix::BindToNetwork(long))
>>> referenced by udp_socket_posix.cc
>>>               thinlto-cache/llvmcache-1C2A14FE4DF0CBFA71B3D3E2B52EF84DEB8656DA:(net::UDPSocketPosix::BindToNetwork(long))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by hello-smile6** [comment]
> Since 100.0.4854.0, there has been a problem that the Link fails to pass after Android compilation. The content is as follows: How to solve it?
> 
> ```
> ld.lld: error: undefined hidden symbol: __system_property_get
> >>> referenced by cpu_model.c
> >>>               cpu_model.c.o:(init_have_lse_atomics) in archive ../../third_party/llvm-build/Release+Asserts/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-aarch64-android.a
> >>> did you mean: __system_property_set
> >>> defined in: ../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/23/libc.so
> 
> ld.lld: error: undefined symbol: net::android::BindToNetwork(int, long)
> >>> referenced by tcp_socket_posix.cc
> >>>               thinlto-cache/llvmcache-D251DAA5ADB3151331297745F2EEB92F6332F6CB:(net::TCPSocketPosix::BindToNetwork(long))
> >>> referenced by udp_socket_posix.cc
> >>>               thinlto-cache/llvmcache-1C2A14FE4DF0CBFA71B3D3E2B52EF84DEB8656DA:(net::UDPSocketPosix::BindToNetwork(long))
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ```

I think you need to make this change on https://chromium.org/

**Comment by hello-smile6** [comment]
How infinity files?

**Review by hello-smile6 — COMMENTED** [review]
Why infinity?

**Comment by emmaki** [comment]
> I suspect it is this fatal patch that prevents LINK from compiling properly on the Android platform. I have posted a BUG at https://bugs.chromium.org/p/chromium/issues/detail?id=1291945, I have tried Android 100.0.4854.0, and even the above version, the compilation link link will appear "error: undefined symbol: net::android::BindToNetwork(int, long)" error

**Comment by hello-smile6** [comment]
@webdev03 Is this ever going to end, do you think?

**Comment by webdev03** [comment]
What's going on

**Pull request closed without merging**
