### PR TITLE
Issue 487422: WebRequest API: allow extensions to read response body

### PR DESCRIPTION
**Pull request by artem-fedorov**
This PR implement the following issue for chrome extensions:
https://bugs.chromium.org/p/chromium/issues/detail?id=487422
Allow extensions to read response body (without modification)
Implementing by adding a new event: `onDataReceived` for extensions API that will notify each time when request get new response data chunk.

### CODE REVIEW

**Comment by artem-fedorov** [comment]
I signed it!

**Comment by uBlock-user** [comment]
@artem-fedorov hello, would submit a PR for editting response body also ?

**Comment by artem-fedorov** [comment]
@uBlock-user 
From this discussion https://groups.google.com/a/chromium.org/d/msg/apps-dev/v176iCmRgSs/06JtyyvRBgAJ I understand that it's not a perfect solution for implementing this feature and `we should have a clearly understood behavior`

**Comment by uBlock-user** [comment]
@artem-fedorov Had a feeling something like this would come up in the dev team, you did your best though, so thanks for the effort.

**Comment by mjonesjr90** [comment]
Hoping this gets merged soon

**Comment by nlpinc** [comment]
Hi 

Can i get some background on this Source code? 

Thanks

**Comment by uBlock-user** [comment]
@aarongable Why was this PR closed ?

**Comment by aarongable** [comment]
Because Chromium does not accept any PRs on Github: notice that this repository is a mirror of https://chromium.googlesource.com/chromium/src. You can send changes for review on https://chromium-review.googlesource.com, as documented in the CONTRIBUTING guide.

**Comment by ccinelli** [comment]
If you do not accept PR here why the `googlebot` does not immediately say it in its comment?

**Comment by nlpinc** [comment]
Is the a project manager for this opensource project?

**Pull request closed without merging**
