### PR TITLE
Initial support for ARM64 Native Compilation

### PR DESCRIPTION
**Pull request by ossdev07**
Dear Team,

Added initial support for  native compilation in ARM64 platform. Disabled nacl tools and binutils for arm64, as they are not supported currently in arm64 platform. 

Please suggest if anything needs to be added.

Thanks in advance.

Regards,

### CODE REVIEW

**Comment by nlpinc** [comment]
Can i get in on this Project in this Decade if possible 

Thanks in Advance

**Comment by ossdev07** [comment]
Hey @nlpinc,

I am really sorry, I didn't get your point 🤔 
Just for the confirmation, I have raised these changes to allow successful Native compilation of chromium over ARM64.

Although, I agree that these are just initial changes and there will be much more based on our fruitful discussions.

Do let me know, how I can go ahead with my intention.

Regards,

**Comment by rhenwood-arm** [comment]
I would find this patch useful. What is the process to get a review from a committer?

**Comment by stephenkyle-ARM** [comment]
I believe all contributions to the Chromium project must follow this guide: https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md

i.e., they don't accept code contributions through Github, this is just a mirror.

**Comment by ossdev07** [comment]
> I believe all contributions to the Chromium project must follow this guide: https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md
> 
> i.e., they don't accept code contributions through Github, this is just a mirror.

Thanks @stephenkyle-ARM . Will follow the document and raise the PR.

**Comment by ossdev07** [comment]
@stephenkyle-ARM I have raised change request in chromium-review site. Please find below link for the same:
https://chromium-review.googlesource.com/c/chromium/src/+/1592630

Could you please suggest any reviewers to add in the same.

Thanks in advance.

**Pull request closed without merging**
